### ISSUE TITLE
您好,想请教一下如何对现有代码进行维护

### ISSUE THREAD

**Issue by ShitMonkey** [wandergis/arcgis-echarts3#1]
目前arcgis-echarts3停留的版本还比较古老,该项目也有很长时间木有更新啦,想请教下个人如何更新main.js内的echarts源代码,小辈也想发布项目定时更新ec3源代码为他人提供帮助

**Comment by aifang** [comment]
源码在arcgis-echarts项目，你找找就找到了，main.js里面打包的东西是china.js和echarts.js你可以看看gulpfile.js看看打包任务即可
感谢wandergis 大神分享……

**Comment by wandergis** [comment]
嗯，echarts3这个跟arcgis-echarts类似的，目前想到一些优化方案，准备后期重构代码

**Comment by ShitMonkey** [comment]
....但是我重新gulp后生成的main.min.js直接替换原来的main.js但并不可用....请问是什么问题呢

**Comment by manooog** [comment]
@wandergis 大神别忘了 重构的事情啊 时间不够的话 我也可以出一份力

**Comment by aifang** [comment]
有段时间研究过echart，我觉得不用打包那么多东西到main里面去，echart是可以骗的，[示例](http://www.echartsjs.com/gallery/editor.html?c=doc-example/scatter-visualMap-piecewise)
改掉 geo: { map: 'china' 之后，只是计算坐标有问题而已，并不是无法显示
      我觉得可以从这里入手，把自己想要的范围和坐标点放进来，坐标点会根据geo.map的范围来计算坐标的相对范围。公司没需求，一直也没折腾echarts-map

**Comment by wandergis** [comment]
忙完这段时间会参照最新的echarts做一个新的出来，最近实在是太忙了
