### ISSUE TITLE
在使用源码gulp封装后

### ISSUE THREAD

**Issue by ShitMonkey** [wandergis/arcgis-echarts3#2]
按照gulpfile.js中的配置封装后生成的main.js和原本已生成的main.js存在出入,替换原main.js后地图内的echarts插件不可用这是为什么呢,我的gulp版本是3.9.1

**Comment by wandergis** [comment]
这里的echarts3的源码由于一开始需要的方法没有在echarts源码公开，因此我手动修改了源码。

**Comment by manooog** [comment]
大致是 echarts.Gro 这个属性没有加上吧？ 但好像不止于此 对于配置项中的geo的处理 应该也自己做了，这部分代码如果是在压缩后的main.js文件中的话 真的不好理解大神的思路
